name: cmssms
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  image_picker: ^1.0.7
  file_picker: ^4.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10
  shared_preferences: ^2.0.8
  printing: ^5.5.9
  geocoding: 3.0.0
  get: ^4.6.1  
  geolocator: ^7.7.1
  http: ^1.2.1
  intl: ^0.19.0
  screenshot: ^3.0.0
  fluttertoast: ^8.2.5
  multi_select_flutter: ^4.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/Home/


  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Light.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
